# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'AH connection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'
- task: UiPathTest@4
  inputs:
    testTarget: 'RPA.Challenge'
    orchestratorConnection: 'AH connection'
    folderName: 'UCare'
    traceLevel: 'Information'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Pack_Test_Pipeline'
    publishLocation: 'Container'

