# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      steps:
      - task: UiPathPack@4
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)'
          outputType: 'Process'
          orchestratorConnection: 'Azure DevOps'
          outputPath: '$(Build.ArtifactStagingDirectory)\output'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop
      - task: UiPathDeploy@4
        displayName: 'UiPath Deploy'
        inputs:
            orchestratorConnection: 'Azure DevOps'
            packagesPath: '$(System.DefaultWorkingDirectory)/_Eduardo-UiPatter.RPA_Challenge (2)/drop/output'
            folderName: AH
            environments: 'UiPath_Dev'
            traceLevel: Information